name: Daily Fortune

on:
  workflow_dispatch:

jobs:
  show-fortune:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13"

      - name: Run fortune
        run: docker run --rm sena2525/daily-fortune:1.0

      - name: Update README
        run: python scripts/update_fortune.py

      - name: Show changes
        run: git diff -- README.md
